// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.1
// source: coords.proto

package protos

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoordsClient is the client API for Coords service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordsClient interface {
	GetCoords(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MessageResponse, error)
}

type coordsClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordsClient(cc grpc.ClientConnInterface) CoordsClient {
	return &coordsClient{cc}
}

func (c *coordsClient) GetCoords(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/RPCGatewayCoords.Coords/GetCoords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordsServer is the server API for Coords service.
// All implementations must embed UnimplementedCoordsServer
// for forward compatibility
type CoordsServer interface {
	GetCoords(context.Context, *empty.Empty) (*MessageResponse, error)
	mustEmbedUnimplementedCoordsServer()
}

// UnimplementedCoordsServer must be embedded to have forward compatible implementations.
type UnimplementedCoordsServer struct {
}

func (UnimplementedCoordsServer) GetCoords(context.Context, *empty.Empty) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoords not implemented")
}
func (UnimplementedCoordsServer) mustEmbedUnimplementedCoordsServer() {}

// UnsafeCoordsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordsServer will
// result in compilation errors.
type UnsafeCoordsServer interface {
	mustEmbedUnimplementedCoordsServer()
}

func RegisterCoordsServer(s grpc.ServiceRegistrar, srv CoordsServer) {
	s.RegisterService(&Coords_ServiceDesc, srv)
}

func _Coords_GetCoords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordsServer).GetCoords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCGatewayCoords.Coords/GetCoords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordsServer).GetCoords(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Coords_ServiceDesc is the grpc.ServiceDesc for Coords service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coords_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RPCGatewayCoords.Coords",
	HandlerType: (*CoordsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCoords",
			Handler:    _Coords_GetCoords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coords.proto",
}
