# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coords.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63oords.proto\x12\x06\x63oords\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x0fMessageResponse\x12\x10\n\x04\x64\x61ta\x18\x01 \x03(\x01\x42\x02\x10\x01\x32\x46\n\x06\x43oords\x12<\n\tGetCoords\x12\x16.google.protobuf.Empty\x1a\x17.coords.MessageResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coords_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGERESPONSE.fields_by_name['data']._options = None
  _MESSAGERESPONSE.fields_by_name['data']._serialized_options = b'\020\001'
  _MESSAGERESPONSE._serialized_start=53
  _MESSAGERESPONSE._serialized_end=88
  _COORDS._serialized_start=90
  _COORDS._serialized_end=160
# @@protoc_insertion_point(module_scope)
